version: '3'                                                                       
services:                                                                          
    container:                                                                        
        container_name: container                                                     
        environment:                                                               
         - ROS_HOSTNAME=container                                                  
        image: ros_container:1.0                                                       
        ports:                                                                     
         - 8083:8080                                                               
        stdin_open: true                                                           
        tty: true
        volumes:
         - ros:/usr/local
volumes:
    ros:
        driver: local
